# Generated by Django 5.1.4 on 2025-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_homepage_options_alter_homepage_about_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='is_delivered',
            field=models.BooleanField(default=False),
        ),
    ]
